<a href="https://colab.research.google.com/github/MegaPlayer64/CodingDojoDataScienceClasses/blob/First-Activities/Cargar_y_filtrar_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Cargar y filtrar datos (Base)**

In [77]:
import pandas as pd
filename = '/content/RailsToTrails_National_Count_Data_week.xlsx'
df = pd.read_excel(filename)
df = df.rename(columns={'Change 2019-2020': 'change_2019_2020'})
pd.options.display.float_format = '{:,.2f}'.format
df['change_2019_2020'] = df['change_2019_2020'] * 100
data_post_july_filter = df[31:]
data_double_change_filter = df.loc[df['change_2019_2020']>=100]
dfnew = pd.concat([data_double_change_filter, data_post_july_filter])
dfnew.head(30)

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,change_2019_2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
7,Week 8,2020-02-17,69492,149876,NaN,115.67,215.67,NaN,NaN,NaN
11,Week 12,2020-03-16,125440,367795,NaN,193.20,293.20,NaN,NaN,NaN
12,Week 13,2020-03-23,136330,372783,NaN,173.00,273.44,NaN,NaN,NaN
13,Week 14,2020-03-30,118784,280728,NaN,136.00,236.33,NaN,NaN,NaN
14,Week 15,2020-04-06,132033,419160,NaN,217.00,317.47,NaN,NaN,NaN
31,Week 32,2020-08-03,180605,239827,NaN,33.00,132.79,NaN,NaN,NaN
32,Week 33,2020-08-10,191450,219279,NaN,15.00,114.54,NaN,NaN,NaN
33,Week 34,2020-08-17,168754,241007,NaN,43.00,142.82,NaN,NaN,NaN
34,Week 35,2020-08-24,176624,273677,NaN,55.00,154.95,NaN,NaN,NaN
35,Week 36,2020-08-31,184806,227918,NaN,23.00,123.33,NaN,NaN,NaN
36,Week 37,2020-09-07,157345,207670,NaN,32.00,131.98,NaN,NaN,NaN
37,Week 38,2020-09-14,152527,207320,NaN,36.00,135.92,NaN,NaN,NaN
38,Week 39,2020-09-21,141072,207918,NaN,47.00,147.38,NaN,NaN,NaN
39,Week 40,2020-09-28,135881,186004,NaN,37.00,136.89,NaN,NaN,NaN
40,Week 41,2020-10-05,132239,182924,NaN,38.00,138.33,NaN,NaN,NaN
41,Week 42,2020-10-12,110816,159246,NaN,44.00,143.70,NaN,NaN,NaN
42,Week 43,2020-10-19,110761,141404,NaN,28.00,127.67,NaN,NaN,NaN
43,Week 44,2020-10-26,109795,147907,NaN,35.00,134.71,NaN,NaN,NaN
44,Week 45,2020-11-02,109766,154502,NaN,41.00,140.76,NaN,NaN,NaN
45,Week 46,2020-11-09,86824,155805,NaN,79.00,179.45,NaN,NaN,NaN
46,Week 47,2020-11-16,88122,97835,NaN,11.00,111.02,NaN,NaN,NaN
47,Week 48,2020-11-23,72380,101036,NaN,40.00,139.59,NaN,NaN,NaN
48,Week 49,2020-11-30,81871,84123,NaN,3.00,102.75,NaN,NaN,NaN
49,Week 50,2020-12-07,68364,92126,NaN,35.00,134.76,NaN,NaN,NaN
50,Week 51,2020-12-14,58063,73188,NaN,26.00,126.05,NaN,NaN,NaN
51,Week 52,2020-12-21,71890,69962,NaN,-3.00,97.32,NaN,26.73,0.51